packages:
  rowi2-plug: !include rowi2-plug.yaml

esphome:
  project:
    name: Kiwi Warmer.Rowi2 Plug
    version: dev

dashboard_import:
  package_import_url: github://vt-vaio/rowi2/rowi2-plug.yaml@main
  import_full_config: true

wifi:
  on_connect:
    - delay: 5s
    - ble.disable:
    - lambda: id(improv_ble_in_progress) = false;
  on_disconnect:
    - ble.enable:

esp32_ble:
  name: rowi2-plug

esp32_improv:
  authorizer: center_button
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
