packages:
  rowi2-plug: !include rowi2-plug.yaml

esphome:
  project:
    name: Kiwi Warmer.Rowi2 Plug
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:
  buffer_size_rx: 1024
  buffer_size_tx: 1024

update:
  - platform: http_request
    name: Rowi2 Plug Firmware
    id: update_http_request
    source: https://github.com/vt-vaio/rowi2/releases/download/stable/manifest.json

dashboard_import:
  package_import_url: github://vt-vaio/rowi2/rowi2-plug.yaml@main
  import_full_config: true

wifi:
  on_connect:
    - delay: 5s
    - ble.disable:
    - lambda: id(improv_ble_in_progress) = false;
  on_disconnect:
    - ble.enable:

esp32_ble:
  name: rowi2-plug

esp32_improv:
  authorizer: center_button
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset"
    entity_category: diagnostic

switch:
  - platform: template
    id: dev_firmware
    name: Use dev firmware
    icon: "mdi:test-tube"
    disabled_by_default: true
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Beta firmware"
      - lambda: id(update_http_request).set_source_url("https://github.com/vt-vaio/rowi2/releases/download/latest-dev/manifest.json");
      - component.update: update_http_request
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      - lambda: id(update_http_request).set_source_url("https://github.com/vt-vaio/rowi2/releases/download/stable/manifest.json");
      - component.update: update_http_request
