# Energy Meter Connection
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 4800
  stop_bits: 1

button:
  - platform: bl0940
    bl0940_id: rowi2
    name: "Cal  Reset"

number:
  - platform: bl0940
    bl0940_id: rowi2
    current_calibration:
      id: current_calibration_ui
      name: "Cal Current"
    voltage_calibration:
      id: voltage_calibration_ui
      name: "Cal Voltage"
    power_calibration:
      id: power_calibration_ui
      name: "Cal Power"
      disabled_by_default: true
    energy_calibration:
      id: energy_calibration_ui
      name: "Cal Energy"
      disabled_by_default: true

sensor:
  - platform: bl0940
    id: rowi2
    uart_id: uart_bus
    tuya_mode: false
    resistor_one: 0.5113
    resistor_shunt: 1.035
    voltage:
      id: bl0940_voltage
      name: 'Voltage'
      accuracy_decimals: 3
    current:
      id: bl0940_current
      name: 'Current'
      accuracy_decimals: 3
    power:
      id: bl0940_power
      name: 'Power'
    energy:
      id: bl0940_energy
      name: 'Energy'
    internal_temperature:
      name: 'bl0940 Internal temperature'
      entity_category: diagnostic
    update_interval: 10s
