# Energy Meter Connection
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 4800
  stop_bits: 1

button:
  - platform: template
    id: calibration_reset
    name: "Cal  Reset"
    entity_category: config
    icon: "mdi:restart"
    on_press:
      - number.set:
          id: current_calibration_ui
          value: 0
      - number.set:
          id: voltage_calibration_ui
          value: 0
      - number.set:
          id: power_calibration_ui
          value: 0
      - number.set:
          id: energy_calibration_ui
          value: 0

number:
  - platform: template
    id: current_calibration_ui
    name: "Cal Current"
    unit_of_measurement: "%"
    min_value: -10
    max_value: 10
    step: 0.01
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:percent"
    entity_category: config
    # disabled_by_default: true
  - platform: template
    id: voltage_calibration_ui
    name: "Cal Voltage"
    unit_of_measurement: "%"
    min_value: -10
    max_value: 10
    step: 0.01
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:percent"
    entity_category: config
    # disabled_by_default: true
  - platform: template
    id: power_calibration_ui
    name: "Cal Power"
    unit_of_measurement: "%"
    min_value: -10
    max_value: 10
    step: 0.01
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:percent"
    entity_category: config
    disabled_by_default: true
  - platform: template
    id: energy_calibration_ui
    name: "Cal Energy"
    unit_of_measurement: "%"
    min_value: -10
    max_value: 10
    step: 0.01
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:percent"
    entity_category: config
    disabled_by_default: true

sensor:
  - platform: bl0940
    uart_id: uart_bus
    tuya_mode: false
    resistor_one: 0.5113
    resistor_shunt: 1.035
    current_calibration: current_calibration_ui
    voltage_calibration: voltage_calibration_ui
    power_calibration: power_calibration_ui
    energy_calibration: energy_calibration_ui
    voltage:
      id: bl0940_voltage
      name: 'Voltage'
      accuracy_decimals: 3
    current:
      id: bl0940_current
      name: 'Current'
      accuracy_decimals: 3
    power:
      id: bl0940_power
      name: 'Power'
    energy:
      id: bl0940_energy
      name: 'Energy'
    internal_temperature:
      name: 'bl0940 Internal temperature'
      entity_category: diagnostic
    update_interval: 10s
