# Energy Meter Connection
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0940
    uart_id: uart_bus
    tuya_mode: false
    resistor_one: 0.511
    voltage:
      name: 'Voltage'
      accuracy_decimals: 3
    current:
      name: 'Current'
      accuracy_decimals: 3
    power:
      name: 'Power'
    energy:
      name: 'Energy'
    internal_temperature:
      name: 'bl0940 Internal temperature'
      entity_category: diagnostic
    update_interval: 10s
